
#ifndef ELECTRONIC_STORE_CONSTANTS_H
#define ELECTRONIC_STORE_CONSTANTS_H

#define SIZE_OF_PACKET_ACK_TYPE 2
#define SIZE_OF_PACKET_LENGTH 4
#define SIZE_OF_PACKET_COUNT 4
#define SIZE_OF_PACKET_PRICE 4
#define SIZE_OF_PACKET_TYPE 2
#define SIZE_OF_ZERO_CHAR 1

#endif //ELECTRONIC_STORE_CONSTANTS_H
