
#ifndef ELECTRONIC_STORE_PACKET_TYPES_H
#define ELECTRONIC_STORE_PACKET_TYPES_H

#define GET_LIST_OF_PRODUCTS_PACKET 6
#define LIST_OF_PRODUCTS_PACKET 2
#define ACKNOWLEDGMENT_PACKET 5
#define ADD_PRODUCT_PACKET 3
#define BUY_PRODUCT_PACKET 4
#define ERROR_PACKET 1

#endif //ELECTRONIC_STORE_PACKET_TYPES_H
