
#ifndef UDP_SERVER_LINUX_TYPES_H
#define UDP_SERVER_LINUX_TYPES_H

// request types
#define RECEIVE_WRITE_REQUEST "RECEIVE WRITE REQUEST"
#define RECEIVE_READ_REQUEST "RECEIVE READ REQUEST"

//data packet types
#define RECEIVE_DATA_PACKET "RECEIVE DATA REQUEST"
#define SEND_DATA_PACKET "SEND DATA PACKET"

//acknowledgment packet types
#define RECEIVE_ACKNOWLEDGMENT_PACKET "RECEIVE ACKNOWLEDGMENT PACKET"
#define SEND_ACKNOWLEDGMENT_PACKET "SEND ACKNOWLEDGMENT PACKET"

#endif //UDP_SERVER_LINUX_TYPES_H
