
#ifndef ELECTRONIC_STORE_ACKNOWLEDGMENT_TYPES_H
#define ELECTRONIC_STORE_ACKNOWLEDGMENT_TYPES_H

#define PRODUCT_WAS_BOUGHT 1
#define PRODUCT_WAS_ADDED 2

#endif //ELECTRONIC_STORE_ACKNOWLEDGMENT_TYPES_H
