
#ifndef NEW_SYSTEM_CLIENT_USER_CHOICE_H
#define NEW_SYSTEM_CLIENT_USER_CHOICE_H

#define GET_LIST_OF_TOPICS 1
#define GET_LIST_OF_NEWS 2
#define GET_NEWS 3
#define ADD_TOPIC 4
#define ADD_NEWS 5
#define QUIT 6

#endif //NEW_SYSTEM_CLIENT_USER_CHOICE_H
