
#ifndef UDP_CLIENT_LINUX_USER_CHOICE_H
#define UDP_CLIENT_LINUX_USER_CHOICE_H

#define DOWNLOAD_FILE_CHOICE 1

#define UPLOAD_FILE_CHOICE 2

#define QUIT_CHOICE 3

#endif //UDP_CLIENT_LINUX_USER_CHOICE_H
