
#ifndef SERVER_LINUX_CONSTANTS_H
#define SERVER_LINUX_CONSTANTS_H

#define MAX_RECEIVED_MESSAGE_SIZE 255

#define MAX_NUMBER_OF_CONNECTED_USERS 1024

#define MAX_NICKNAME_SIZE 10

#define TIME_SIZE 10

#endif //SERVER_LINUX_CONSTANTS_H