#ifndef UDP_SERVER_LINUX_ERROR_CODES_H
#define UDP_SERVER_LINUX_ERROR_CODES_H

#define NOT_DEFINED 0
#define FILE_NOT_FOUND 1
#define ACCESS_VIOLATION 2
#define DISK_FULL_OR_ALLOCATION_EXCEEDED 3
#define ILLEGAL_TFTP_OPERATION 4
#define UNKNOWN_TRANSFER_ID 5
#define FILE_ALREADY_EXISTS 6
#define NO_SUCH_USER 7

#endif //UDP_SERVER_LINUX_ERROR_CODES_H
