
#ifndef ELECTRONIC_STORE_SERVER_ACTIONS_WITH_PRODUCT_H
#define ELECTRONIC_STORE_SERVER_ACTIONS_WITH_PRODUCT_H

#define ADD_PRODUCT 1
#define BUY_PRODUCT 2

#endif //ELECTRONIC_STORE_SERVER_ACTIONS_WITH_PRODUCT_H
