
#ifndef CLIENT_LINUX_CONSTANTS_H
#define CLIENT_LINUX_CONSTANTS_H

#define TIME_SIZE 10

#define MAX_MESSAGE_LENGTH COLS-3-TIME_SIZE-MAX_NICKNAME_SIZE

#define OUTPUT_WINDOW_HEIGHT LINES-5

#define INPUT_WINDOW_HEIGHT 3

#define MAX_NICKNAME_SIZE 10

#define MESSAGE_SIZE 256

#endif //CLIENT_LINUX_CONSTANTS_H
