
#ifndef NEW_SYSTEM_CLIENT_ERROR_TYPES_H
#define NEW_SYSTEM_CLIENT_ERROR_TYPES_H

#define LACK_OF_NEWS_TOPIC 1
#define NO_NEWS_WITH_THIS_HEADLINE 2
#define ADDING_EXISTING_NEWS_TOPIC 3
#define ADDITION_OF_NEWS_WITH_EXISTING_HEADER 4

#endif //NEW_SYSTEM_CLIENT_ERROR_TYPES_H
