
#ifndef NEW_SYSTEM_CLIENT_PACKET_TYPES_H
#define NEW_SYSTEM_CLIENT_PACKET_TYPES_H

#define GET_LIST_OF_TOPICS_PACKET 1
#define GET_LIST_OF_NEWS_PACKET 2
#define GET_NEWS_PACKET 3
#define ADD_TOPIC_PACKET 4
#define ADD_NEWS_PACKET 5
#define LIST_OF_TOPICS_PACKET 6
#define LIST_OF_NEWS_PACKET 7
#define NEWS_PACKET 8
#define ERROR_PACKET 9
#define ACKNOWLEDGMENT_PACKET 10

#endif //NEW_SYSTEM_CLIENT_PACKET_TYPES_H
