
#ifndef UDP_SERVER_LINUX_CONSTANTS_H
#define UDP_SERVER_LINUX_CONSTANTS_H

#define PACKET_BLOCK_NUMBER_SIZE 2

#define MAX_PACKET_SIZE 516

#define PACKET_TYPE_SIZE 2

#endif //UDP_SERVER_LINUX_CONSTANTS_H
