
#ifndef UDP_SERVER_LINUX_PACKET_TYPES_H
#define UDP_SERVER_LINUX_PACKET_TYPES_H

#define DTG_READ_REQUEST 1
#define DTG_WRITE_REQUEST 2
#define DTG_DATA 3
#define DTG_ACKNOWLEDGMENT 4
#define DTG_ERROR 5

#endif //UDP_SERVER_LINUX_PACKET_TYPES_H
