
#ifndef NEW_SYSTEM_CLIENT_CONSTANTS_H
#define NEW_SYSTEM_CLIENT_CONSTANTS_H

#define SIZE_OF_PACKET_LENGTH 4
#define SIZE_OF_PACKET_TYPE 2
#define SIZE_OF_PACKET_ZERO_BYTE 1
#define SIZE_OF_ERR_TYPE 2
#define SIZE_OF_ACKNOWLEDGMENT_TYPE 2

#define MAX_INPUT_USER_SIZE 256

#endif //NEW_SYSTEM_CLIENT_CONSTANTS_H
